version: "3"

services:
  apache:
    build: frontend
    ports:
      - 80:80
  dotnet:
    build: history
    depends_on:
      - database
    ports:
      - 5000:80
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "Microsoft_SQL_Server_CloudAPIs"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<Insert password>
